### ISSUE TITLE
Setting Density

### ISSUE THREAD

**Issue by feichaiyu** [vzyrianov/LidarDM#1]
This is a very interesting job. May I ask where can I set the density of the generated point cloud?

**Comment by hungdche** [comment]
Thank you for your interest! You can set the density of Kitti generated point cloud by tweaking these parameters here: https://github.com/vzyrianov/LidarDM/blob/fc0a8e17ad0e80e510227a024ab01c1313a13f45/lidardm/lidar_generation/scene_composition/utils/raycast_configs.py#L17

**Comment by feichaiyu** [comment]
> Thank you for your interest! You can set the density of Kitti generated point cloud by tweaking these parameters here:
> 
> https://github.com/vzyrianov/LidarDM/blob/fc0a8e17ad0e80e510227a024ab01c1313a13f45/lidardm/lidar_generation/scene_composition/utils/raycast_configs.py#L17

Thank you for your response. Does adjusting these parameters necessitate retraining the model? The cost of four Nvidia A100 40GB GPUs is prohibitively high for me to afford, which is disheartening.

**Comment by hungdche** [comment]
Hi. This change does not require retraining any learnable components of our pipeline (scene generation or raydropping)!

**Comment by hungdche** [comment]
I will close this for now. Please reopen if you have any questions.
