### ISSUE TITLE
Retrain VAE Model

### ISSUE THREAD

**Issue by HaiyunW** [vzyrianov/LidarDM#3]
Hello! How can I retrain the VAE model and decode it on kitti-360 dataset for other research? Could you give me some instructions? I have sent a email to you, but got no reply!

**Comment by vzyrianov** [comment]
Take a look here: [https://github.com/vzyrianov/LidarDM/blob/main/docs/SCENE_GENERATION.md](https://github.com/vzyrianov/LidarDM/blob/main/docs/SCENE_GENERATION.md)
