### ISSUE TITLE
May I ask the hardware requirements for this job?

### ISSUE THREAD

**Issue by eggman-1024** [vzyrianov/LidarDM#7]

**Comment by hungdche** [comment]
For training we use 8 A100 GPUs. For just inference, I tried with a RTX 4080 and it worked fine.

**Comment by eggman-1024** [comment]
> For training we use 8 A100 GPUs. For just inference, I tried with a RTX 4080 and it worked fine.

Thanks! Also, I sent an email to Vlas a few days ago, but he didn't reply to me. Will he reply?

**Comment by vzyrianov** [comment]
We use 4 A100s for training. Additional details are in the paper under "Training Details."

**Comment by eggman-1024** [comment]
> We use 4 A100s for training. Additional details are in the paper under "Training Details."

Thank you for your answer! By the way, I have sent an email to you, may I ask if you have time to reply to me? Thank you!

**Comment by eggman-1024** [comment]
> > We use 4 A100s for training. Additional details are in the paper under "Training Details."
> 
> Thank you for your answer! By the way, I have sent an email to you, may I ask if you have time to reply to me? Thank you!
My email is rtzhang1024@gmail.com, and the topic is "Some qustions about Lidar point cloud generation from a master student from Jinan University"
