### ISSUE TITLE
raise error when run the preprocess script of kitti

### ISSUE THREAD

**Issue by eggman-1024** [vzyrianov/LidarDM#8]
![c257bc40c29d7495bcd8a100d03b448](https://github.com/vzyrianov/LidarDM/assets/79270109/84b216a2-5348-417d-9cf1-fb43a6cd0775)
May I ask if this directory structure is correct? 

What do the terms "train" and "train_full" in the "data_3d_bboxes" folder mean?

I use this"python scripts/dataset/preprocess/kitti360_preprocess.py --dataset_path _datasets/kitti/ --seq 0 1 2 3 4 5 6 7 9 10 --out_dir _datasets/kitti/", 
but it raise the error: 
  "File "/home/zhangruitao/projects/LidarDM/scripts/dataset/preprocess/kitti360_preprocess.py", line 37, in <module>
      annotation3D = Annotation3D(bbox_file, sequence_name)
    File "/home/zhangruitao/anaconda3/envs/lidardm/lib/python3.10/site-packages/kitti360scripts/helpers/annotation.py", line 362, in __init__
      raise RuntimeError('%s does not exist! Please specify KITTI360_DATASET in your environment path.' % labelPath)
  RuntimeError: ['_datasets/kitti/data_3d_bboxes/train/2013_05_28_drive_0000_sync.xml', '_datasets/kitti/data_3d_bboxes/train_full/2013_05_28_drive_0000_sync.xml'] does not exist! Please specify KITTI360_DATASET in your environment path."
  
  In my opinion, It seems to be caused by more than one folder under the "data_3d_bboxes" folder

**Comment by hungdche** [comment]
The `train` and `train_full` come with the KITTI-360 dataset. I remember I had to get rid of one of the two, but I couldn't remember which (can double check later tonight). Also, make sure to set your `KITTI360_DATASET` environment ([instruction](https://github.com/autonomousvision/kitti360scripts#usage)).

**Comment by huoxingsenlin** [comment]
May I have a question that which folder you got rid of? Cause we have the same problem about the 'RuntimeError: ['_datasets/kitti/data_3d_bboxes/train/2013_05_28_drive_0000_sync.xml', '_datasets/kitti/data_3d_bboxes/train_full/2013_05_28_drive_0000_sync.xml'] does not exist!'

**Comment by hungdche** [comment]
I deleted the `train_full` folder, as the `train` folder contains bounding boxes with `semanticId`, which we use [here](https://github.com/vzyrianov/LidarDM/blob/162896d2387511c1e2ff6b633b7eba89fb14bf0a/scripts/dataset/raycast/kitti360_raycast.py#L91-L94).
